// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/satellite.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// First: base types everyone depends on
type ParsedTLE struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SatelliteNum   int32                  `protobuf:"varint,1,opt,name=satellite_num,json=satelliteNum,proto3" json:"satellite_num,omitempty"`
	Classification string                 `protobuf:"bytes,2,opt,name=classification,proto3" json:"classification,omitempty"`
	EpochYear      int32                  `protobuf:"varint,3,opt,name=epoch_year,json=epochYear,proto3" json:"epoch_year,omitempty"`
	EpochDays      float64                `protobuf:"fixed64,4,opt,name=epoch_days,json=epochDays,proto3" json:"epoch_days,omitempty"`
	Bstar          float64                `protobuf:"fixed64,5,opt,name=bstar,proto3" json:"bstar,omitempty"`
	Inclination    float64                `protobuf:"fixed64,6,opt,name=inclination,proto3" json:"inclination,omitempty"`
	RightAscension float64                `protobuf:"fixed64,7,opt,name=right_ascension,json=rightAscension,proto3" json:"right_ascension,omitempty"`
	Eccentricity   float64                `protobuf:"fixed64,8,opt,name=eccentricity,proto3" json:"eccentricity,omitempty"`
	ArgPerigee     float64                `protobuf:"fixed64,9,opt,name=arg_perigee,json=argPerigee,proto3" json:"arg_perigee,omitempty"`
	MeanAnomaly    float64                `protobuf:"fixed64,10,opt,name=mean_anomaly,json=meanAnomaly,proto3" json:"mean_anomaly,omitempty"`
	MeanMotion     float64                `protobuf:"fixed64,11,opt,name=mean_motion,json=meanMotion,proto3" json:"mean_motion,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParsedTLE) Reset() {
	*x = ParsedTLE{}
	mi := &file_api_satellite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedTLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTLE) ProtoMessage() {}

func (x *ParsedTLE) ProtoReflect() protoreflect.Message {
	mi := &file_api_satellite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTLE.ProtoReflect.Descriptor instead.
func (*ParsedTLE) Descriptor() ([]byte, []int) {
	return file_api_satellite_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedTLE) GetSatelliteNum() int32 {
	if x != nil {
		return x.SatelliteNum
	}
	return 0
}

func (x *ParsedTLE) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *ParsedTLE) GetEpochYear() int32 {
	if x != nil {
		return x.EpochYear
	}
	return 0
}

func (x *ParsedTLE) GetEpochDays() float64 {
	if x != nil {
		return x.EpochDays
	}
	return 0
}

func (x *ParsedTLE) GetBstar() float64 {
	if x != nil {
		return x.Bstar
	}
	return 0
}

func (x *ParsedTLE) GetInclination() float64 {
	if x != nil {
		return x.Inclination
	}
	return 0
}

func (x *ParsedTLE) GetRightAscension() float64 {
	if x != nil {
		return x.RightAscension
	}
	return 0
}

func (x *ParsedTLE) GetEccentricity() float64 {
	if x != nil {
		return x.Eccentricity
	}
	return 0
}

func (x *ParsedTLE) GetArgPerigee() float64 {
	if x != nil {
		return x.ArgPerigee
	}
	return 0
}

func (x *ParsedTLE) GetMeanAnomaly() float64 {
	if x != nil {
		return x.MeanAnomaly
	}
	return 0
}

func (x *ParsedTLE) GetMeanMotion() float64 {
	if x != nil {
		return x.MeanMotion
	}
	return 0
}

type TLEPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	Parsed        *ParsedTLE             `protobuf:"bytes,4,opt,name=parsed,proto3" json:"parsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLEPackage) Reset() {
	*x = TLEPackage{}
	mi := &file_api_satellite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLEPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLEPackage) ProtoMessage() {}

func (x *TLEPackage) ProtoReflect() protoreflect.Message {
	mi := &file_api_satellite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLEPackage.ProtoReflect.Descriptor instead.
func (*TLEPackage) Descriptor() ([]byte, []int) {
	return file_api_satellite_proto_rawDescGZIP(), []int{1}
}

func (x *TLEPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TLEPackage) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *TLEPackage) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

func (x *TLEPackage) GetParsed() *ParsedTLE {
	if x != nil {
		return x.Parsed
	}
	return nil
}

// Then: refresh (simple, no deps)
type RefreshCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId   string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	CheckTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=check_time,json=checkTime,proto3" json:"check_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshCheck) Reset() {
	*x = RefreshCheck{}
	mi := &file_api_satellite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshCheck) ProtoMessage() {}

func (x *RefreshCheck) ProtoReflect() protoreflect.Message {
	mi := &file_api_satellite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshCheck.ProtoReflect.Descriptor instead.
func (*RefreshCheck) Descriptor() ([]byte, []int) {
	return file_api_satellite_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshCheck) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *RefreshCheck) GetCheckTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckTime
	}
	return nil
}

// Then: change (depends on TLEPackage)
type TLEChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatelliteId   string                 `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	NewTle        *TLEPackage            `protobuf:"bytes,2,opt,name=new_tle,json=newTle,proto3" json:"new_tle,omitempty"`
	ChangeTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=change_time,json=changeTime,proto3" json:"change_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLEChange) Reset() {
	*x = TLEChange{}
	mi := &file_api_satellite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLEChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLEChange) ProtoMessage() {}

func (x *TLEChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_satellite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLEChange.ProtoReflect.Descriptor instead.
func (*TLEChange) Descriptor() ([]byte, []int) {
	return file_api_satellite_proto_rawDescGZIP(), []int{3}
}

func (x *TLEChange) GetSatelliteId() string {
	if x != nil {
		return x.SatelliteId
	}
	return ""
}

func (x *TLEChange) GetNewTle() *TLEPackage {
	if x != nil {
		return x.NewTle
	}
	return nil
}

func (x *TLEChange) GetChangeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangeTime
	}
	return nil
}

// Finally: future extension (depends on TLEPackage)
type ExtendedTLE struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClassicTle        *TLEPackage            `protobuf:"bytes,1,opt,name=classic_tle,json=classicTle,proto3" json:"classic_tle,omitempty"`
	Line3Raw          string                 `protobuf:"bytes,2,opt,name=line3_raw,json=line3Raw,proto3" json:"line3_raw,omitempty"`
	BallisticCoeff    float64                `protobuf:"fixed64,3,opt,name=ballistic_coeff,json=ballisticCoeff,proto3" json:"ballistic_coeff,omitempty"`
	MeanMotionDdot    float64                `protobuf:"fixed64,4,opt,name=mean_motion_ddot,json=meanMotionDdot,proto3" json:"mean_motion_ddot,omitempty"`
	CatalogIdExtended int64                  `protobuf:"varint,5,opt,name=catalog_id_extended,json=catalogIdExtended,proto3" json:"catalog_id_extended,omitempty"` // repeated ... = 6; if needed later
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExtendedTLE) Reset() {
	*x = ExtendedTLE{}
	mi := &file_api_satellite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendedTLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendedTLE) ProtoMessage() {}

func (x *ExtendedTLE) ProtoReflect() protoreflect.Message {
	mi := &file_api_satellite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendedTLE.ProtoReflect.Descriptor instead.
func (*ExtendedTLE) Descriptor() ([]byte, []int) {
	return file_api_satellite_proto_rawDescGZIP(), []int{4}
}

func (x *ExtendedTLE) GetClassicTle() *TLEPackage {
	if x != nil {
		return x.ClassicTle
	}
	return nil
}

func (x *ExtendedTLE) GetLine3Raw() string {
	if x != nil {
		return x.Line3Raw
	}
	return ""
}

func (x *ExtendedTLE) GetBallisticCoeff() float64 {
	if x != nil {
		return x.BallisticCoeff
	}
	return 0
}

func (x *ExtendedTLE) GetMeanMotionDdot() float64 {
	if x != nil {
		return x.MeanMotionDdot
	}
	return 0
}

func (x *ExtendedTLE) GetCatalogIdExtended() int64 {
	if x != nil {
		return x.CatalogIdExtended
	}
	return 0
}

var File_api_satellite_proto protoreflect.FileDescriptor

const file_api_satellite_proto_rawDesc = "" +
	"\n" +
	"\x13api/satellite.proto\x12\fsatellite.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\tParsedTLE\x12#\n" +
	"\rsatellite_num\x18\x01 \x01(\x05R\fsatelliteNum\x12&\n" +
	"\x0eclassification\x18\x02 \x01(\tR\x0eclassification\x12\x1d\n" +
	"\n" +
	"epoch_year\x18\x03 \x01(\x05R\tepochYear\x12\x1d\n" +
	"\n" +
	"epoch_days\x18\x04 \x01(\x01R\tepochDays\x12\x14\n" +
	"\x05bstar\x18\x05 \x01(\x01R\x05bstar\x12 \n" +
	"\vinclination\x18\x06 \x01(\x01R\vinclination\x12'\n" +
	"\x0fright_ascension\x18\a \x01(\x01R\x0erightAscension\x12\"\n" +
	"\feccentricity\x18\b \x01(\x01R\feccentricity\x12\x1f\n" +
	"\varg_perigee\x18\t \x01(\x01R\n" +
	"argPerigee\x12!\n" +
	"\fmean_anomaly\x18\n" +
	" \x01(\x01R\vmeanAnomaly\x12\x1f\n" +
	"\vmean_motion\x18\v \x01(\x01R\n" +
	"meanMotion\"}\n" +
	"\n" +
	"TLEPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\x12/\n" +
	"\x06parsed\x18\x04 \x01(\v2\x17.satellite.v1.ParsedTLER\x06parsed\"l\n" +
	"\fRefreshCheck\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x129\n" +
	"\n" +
	"check_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckTime\"\x9e\x01\n" +
	"\tTLEChange\x12!\n" +
	"\fsatellite_id\x18\x01 \x01(\tR\vsatelliteId\x121\n" +
	"\anew_tle\x18\x02 \x01(\v2\x18.satellite.v1.TLEPackageR\x06newTle\x12;\n" +
	"\vchange_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"changeTime\"\xe8\x01\n" +
	"\vExtendedTLE\x129\n" +
	"\vclassic_tle\x18\x01 \x01(\v2\x18.satellite.v1.TLEPackageR\n" +
	"classicTle\x12\x1b\n" +
	"\tline3_raw\x18\x02 \x01(\tR\bline3Raw\x12'\n" +
	"\x0fballistic_coeff\x18\x03 \x01(\x01R\x0eballisticCoeff\x12(\n" +
	"\x10mean_motion_ddot\x18\x04 \x01(\x01R\x0emeanMotionDdot\x12.\n" +
	"\x13catalog_id_extended\x18\x05 \x01(\x03R\x11catalogIdExtendedB&Z$github.com/TylerWerne40/sat-track/pbb\x06proto3"

var (
	file_api_satellite_proto_rawDescOnce sync.Once
	file_api_satellite_proto_rawDescData []byte
)

func file_api_satellite_proto_rawDescGZIP() []byte {
	file_api_satellite_proto_rawDescOnce.Do(func() {
		file_api_satellite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_satellite_proto_rawDesc), len(file_api_satellite_proto_rawDesc)))
	})
	return file_api_satellite_proto_rawDescData
}

var file_api_satellite_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_satellite_proto_goTypes = []any{
	(*ParsedTLE)(nil),             // 0: satellite.v1.ParsedTLE
	(*TLEPackage)(nil),            // 1: satellite.v1.TLEPackage
	(*RefreshCheck)(nil),          // 2: satellite.v1.RefreshCheck
	(*TLEChange)(nil),             // 3: satellite.v1.TLEChange
	(*ExtendedTLE)(nil),           // 4: satellite.v1.ExtendedTLE
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_satellite_proto_depIdxs = []int32{
	0, // 0: satellite.v1.TLEPackage.parsed:type_name -> satellite.v1.ParsedTLE
	5, // 1: satellite.v1.RefreshCheck.check_time:type_name -> google.protobuf.Timestamp
	1, // 2: satellite.v1.TLEChange.new_tle:type_name -> satellite.v1.TLEPackage
	5, // 3: satellite.v1.TLEChange.change_time:type_name -> google.protobuf.Timestamp
	1, // 4: satellite.v1.ExtendedTLE.classic_tle:type_name -> satellite.v1.TLEPackage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_satellite_proto_init() }
func file_api_satellite_proto_init() {
	if File_api_satellite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_satellite_proto_rawDesc), len(file_api_satellite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_satellite_proto_goTypes,
		DependencyIndexes: file_api_satellite_proto_depIdxs,
		MessageInfos:      file_api_satellite_proto_msgTypes,
	}.Build()
	File_api_satellite_proto = out.File
	file_api_satellite_proto_goTypes = nil
	file_api_satellite_proto_depIdxs = nil
}
